### ISSUE TITLE
"canvas is not a constructor"

### ISSUE THREAD

**Issue by lakeinchina** [godmodelabs/ejecta-v8#12]
I compile ejecta-v8 as a module of ejecta-v8-sample.when i 'run in Ejecta-v8 View' , it crash.
plasma.js:
```js
	var canvas = require('canvas');
	console.log("canvasA="+canvas);
	var c = new canvas(view);
```
ag.boersego.bgjs.sample I/BGJSV8Engine-jni:  viewCreated called [object Arguments]
ag.boersego.bgjs.sample I/BGJSV8Engine-jni:  canvasA=[object HTMLCanvasElement]
    
beginning of crash
ag.boersego.bgjs.sample E/AndroidRuntime: FATAL EXCEPTION: Thread-4296
    Process: ag.boersego.bgjs.sample, PID: 23679
    ag.boersego.bgjs.V8Exception: An exception was thrown in JavaScript
        at ag.boersego.bgjs.JNIV8Function._callAsV8Function(Native Method)
        at ag.boersego.bgjs.JNIV8Function.callAsV8Function(JNIV8Function.java:22)
        at ag.boersego.bgjs.sample.DemoEjectaFragment.initializeV8(DemoEjectaFragment.java:76)
        at ag.boersego.bgjs.sample.DemoEjectaFragment.access$200(DemoEjectaFragment.java:24)
        at ag.boersego.bgjs.sample.DemoEjectaFragment$1$1.onGLCreated(DemoEjectaFragment.java:97)
        at ag.boersego.bgjs.V8TextureView$RenderThread.run(V8TextureView.java:743)
     Caused by: ag.boersego.bgjs.V8JSException: [TypeError] **canvas is not a constructor**
        at global.startPlasma(js/plasma.js:106)

any help?

**Comment by lakeinchina** [comment]
well,canvas is a function,so I replaced
```js
var c = new canvas(view);
```
with
```js
var c = canvas(view);
```
And it works,but why?

**Comment by unverbraucht** [comment]
These are two different ways of calling constructors in v8 native-backed functions. I'll look into it, thanks.
